FROM oven/bun:1 AS base
WORKDIR /app

# Install dependencies
FROM base AS install
COPY package.json ./
RUN bun install

# Copy application and run
FROM base AS release
COPY --from=install /app/node_modules ./node_modules
COPY . .

EXPOSE 3000
USER bun
ENTRYPOINT ["bun", "run", "src/index.ts"]
