FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum* ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /bin/server cmd/web/main.go

FROM alpine:latest AS runner

WORKDIR /app

RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /bin/server /app/server
COPY --from=builder /app/views /app/views

EXPOSE 3000

CMD ["/app/server"]
