BINARY_NAME={{ .SafeName }}

.PHONY: all build run test clean

all: build

build:
	go build -ldflags="-s -w" -o bin/$(BINARY_NAME) main.go

run:
	go run main.go

interactive:
	go run main.go interactive

test:
	go test -v ./...

clean:
	rm -rf bin/
