FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum* ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /bin/app main.go

FROM alpine:latest AS runner

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY --from=builder /bin/app /app/tui-app

ENTRYPOINT ["/app/tui-app"]
