package generator

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// getDrizzleFiles returns the list of files generated by Drizzle ORM addon
func getDrizzleFiles(config ProjectConfig, baseDir string) []string {
	if !config.Addons.Drizzle {
		return nil
	}
	return []string{
		filepath.Join(baseDir, "drizzle.config.ts"),
		filepath.Join(baseDir, "src", "db", "index.ts"),
		filepath.Join(baseDir, "src", "db", "schema.ts"),
	}
}

// injectNodeScripts injects npm scripts into package.json without overwriting existing ones
func injectNodeScripts(packageJSONPath string, scripts map[string]string) error {
	data, err := os.ReadFile(packageJSONPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	data = bytes.TrimPrefix(data, []byte("\xef\xbb\xbf"))

	var pkgMap map[string]interface{}
	if err := json.Unmarshal(data, &pkgMap); err != nil {
		return err
	}

	var currentScripts map[string]interface{}
	if existing, ok := pkgMap["scripts"].(map[string]interface{}); ok {
		currentScripts = existing
	} else {
		currentScripts = make(map[string]interface{})
	}

	for k, v := range scripts {
		if _, exists := currentScripts[k]; !exists {
			currentScripts[k] = v
		}
	}
	pkgMap["scripts"] = currentScripts

	updated, err := json.MarshalIndent(pkgMap, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(packageJSONPath, append(updated, '\n'), 0644)
}

// generateDrizzleAddon injects Drizzle ORM schema, client, config and dependencies
func generateDrizzleAddon(config ProjectConfig, baseDir string) error {
	if !config.Addons.Drizzle {
		return nil
	}

	db := strings.ToLower(strings.TrimSpace(config.Addons.Database))
	isSQLite := db == "sqlite"

	var drizzleConfigContent string
	var schemaContent string
	var clientContent string

	if isSQLite {
		drizzleConfigContent = `import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './src/db/schema.ts',
  out: './drizzle',
  dialect: 'sqlite',
  dbCredentials: {
    url: process.env.DATABASE_URL || './sqlite.db',
  },
});
`
		schemaContent = `import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
`
		clientContent = `import { drizzle } from 'drizzle-orm/better-sqlite3';
import Database from 'better-sqlite3';
import * as schema from './schema';

const sqlite = new Database(process.env.DATABASE_URL || './sqlite.db');

export const db = drizzle(sqlite, { schema });
export type DatabaseInstance = typeof db;
`
	} else {
		// Default to PostgreSQL dialect
		drizzleConfigContent = `import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './src/db/schema.ts',
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/app',
  },
});
`
		schemaContent = `import { pgTable, serial, text, timestamp, varchar } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
`
		clientContent = `import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from './schema';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/app',
});

export const db = drizzle(pool, { schema });
export type DatabaseInstance = typeof db;
`
	}

	if err := writeAddonFile(baseDir, "drizzle.config.ts", drizzleConfigContent); err != nil {
		return err
	}
	if err := writeAddonFile(baseDir, filepath.Join("src", "db", "schema.ts"), schemaContent); err != nil {
		return err
	}
	if err := writeAddonFile(baseDir, filepath.Join("src", "db", "index.ts"), clientContent); err != nil {
		return err
	}

	pkgPath := filepath.Join(baseDir, "package.json")
	nodeDeps := make(map[string]string)
	nodeDevDeps := make(map[string]string)

	nodeDeps["drizzle-orm"] = "^0.45.1"
	nodeDevDeps["drizzle-kit"] = "^0.30.5"

	if isSQLite {
		nodeDeps["better-sqlite3"] = "^11.8.1"
		nodeDevDeps["@types/better-sqlite3"] = "^7.6.12"
	} else {
		nodeDeps["pg"] = "^8.12.0"
		nodeDevDeps["@types/pg"] = "^8.11.6"
	}

	if err := injectNodeDependencies(pkgPath, nodeDeps, nodeDevDeps); err != nil {
		return fmt.Errorf("failed injecting drizzle node dependencies: %w", err)
	}

	scripts := map[string]string{
		"db:generate": "drizzle-kit generate",
		"db:migrate":  "drizzle-kit migrate",
		"db:push":     "drizzle-kit push",
		"db:studio":   "drizzle-kit studio",
	}
	if err := injectNodeScripts(pkgPath, scripts); err != nil {
		return fmt.Errorf("failed injecting drizzle scripts: %w", err)
	}

	return nil
}
